name: EvoSuite Test Generation

on:
  workflow_dispatch:  # lo attivi manualmente da GitHub

jobs:
  evosuite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download EvoSuite
        run: |
          mkdir -p tools/evosuite
          wget -O tools/evosuite/evosuite-1.2.0.jar https://github.com/EvoSuite/evosuite/releases/download/v1.2.0/evosuite-1.2.0.jar

      - name: Clean all old builds
        run: find . -name target -type d -exec rm -rf {} +

      - name: Compile only bookkeeper-server and generate classpath
        working-directory: bookkeeper-server
        run: |
          mvn clean compile -pl . -am -DskipTests -Dmaven.compiler.release=11 -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 -DforceJavacCompilerUse=true
          mvn dependency:build-classpath -Dmdep.outputFile=cp.txt

      - name: Run EvoSuite for BufferedChannel
        working-directory: bookkeeper-server
        run: |
          FULL_CP="target/classes:$(cat cp.txt)"
          java -jar ../tools/evosuite/evosuite-1.2.0.jar \
            -class org.apache.bookkeeper.bookie.BufferedChannel \
            -projectCP "$FULL_CP" \
            -Dsandbox=false \
            -Dsearch_budget=60 || true

      - name: Upload generated tests
        uses: actions/upload-artifact@v4
        with:
          name: evosuite-tests
          path: bookkeeper-server/evosuite-tests/
