name: EvoSuite Test Generation

on:
  workflow_dispatch:

jobs:
  evosuite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Clean local Maven repo for BookKeeper
        run: rm -rf ~/.m2/repository/org/apache/bookkeeper

      - name: Download EvoSuite
        run: |
          mkdir -p tools/evosuite
          wget -O tools/evosuite/evosuite-1.2.0.jar https://github.com/EvoSuite/evosuite/releases/download/v1.2.0/evosuite-1.2.0.jar

      - name: Compile bookkeeper-server and generate classpath
        working-directory: bookkeeper-server
        run: |
          mvn clean install -DskipTests
          mvn dependency:build-classpath -Dmdep.outputFile=cp.txt

      - name: Run EvoSuite for BufferedChannel
        working-directory: bookkeeper-server
        run: |
          FULL_CP="target/classes:$(cat cp.txt)"
          java -jar ../tools/evosuite/evosuite-1.2.0.jar \
            -class org.apache.bookkeeper.bookie.BufferedChannel \
            -projectCP "$FULL_CP" \
            -Dsandbox=false \
            -Dsearch_budget=60

      - name: Upload generated tests
        uses: actions/upload-artifact@v4
        with:
          name: evosuite-tests
          path: bookkeeper-server/evosuite-tests/
