name: PIT Mutation Testing - Dennis

on:
  push:
    branches: [ testing-project-ISW2 ]

jobs:
  pit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bookkeeper-server  # directory dove lanciare mvn

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Run PIT Mutation Testing
        run: mvn clean test-compile org.pitest:pitest-maven:1.4.11:mutationCoverage

      - name: Upload PIT Report
        uses: actions/upload-artifact@v3
        with:
          name: pit-report
          path: bookkeeper-server/target/pit-reports
